### ISSUE TITLE
Custom timeoutInterval doesn't work

### ISSUE THREAD

**Issue by nickasd** [daltoniam/Starscream#687]
I'm trying to increase the default `timeoutInterval` of 1 minute to 10 minutes with this code:
```
var request = URLRequest(url: URL(string: "ws://localhost:80/ws")!)
request.timeoutInterval = 600
let ws = WebSocket(request: request)
```
Still this doesn't work. Any idea what I might be doing wrong? After 1 minute, the `onDisconnect` handler is called with `error = nil`.

**Comment by daltoniam** [comment]
That is the right setup, but the disconnect code isn't "builtin" to the API that is using it (old foundation API). I refactored that logic in 4.0.0 to help with disconnect time and started using the Network framework which does support timeouts. Upgrading should resolve the issue unless it is related to something other than the timeout in the socket API.

**Comment by nickasd** [comment]
Thanks, it works now.

**Comment by nickasd** [comment]
Sorry, I thought it worked but it still doesn't. Even when setting `request.timeoutInterval = 5` the timeout happens at 60 seconds. Have you tried it?

**Comment by nickasd** [comment]
Can somebody please reopen this issue?
